#use golang basic image
FROM golang:1.18-alpine

#set the working directory inside the container
WORKDIR /usr/src/app 

#copy Go mod and sum files
COPY go.mod go.sum ./

#Download dependencies
RUN go mod tidy

#Copy the rest of the application code 
COPY . .

#Expose port 8080 for the go API
EXPOSE 8080

#Run the go application
CMD ["go", "run","main.go"]